 
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type GlobalRule = PlacementRule & {
  /**
   * @minItems 1
   */
  appliesToTags?: [string, ...string[]];
  area?:
    | {
        type: "circle";
        /**
         * @minItems 2
         * @maxItems 2
         */
        center: [number, number];
        radius: number;
        [k: string]: unknown;
      }
    | {
        type: "bbox";
        /**
         * @minItems 4
         * @maxItems 4
         */
        coordinates: [number, number, number, number];
        [k: string]: unknown;
      }
    | {
        type: "polygon";
        /**
         * @minItems 3
         */
        coordinates: [
          [number, number, ...number[]],
          [number, number, ...number[]],
          [number, number, ...number[]],
          ...[number, number, ...number[]][]
        ];
        [k: string]: unknown;
      };
  [k: string]: unknown;
};

/**
 * Formal description for global placement rules for AR-Objects in ARVal.
 */
export interface GlobalConstraints {
  /**
   * Human-readable name of the constraint set (e.g. 'Fire truck safety space')
   */
  name: string;
  /**
   * Scope of the rules, must be 'global' for AGCS.
   */
  scope: "global";
  $comment?: "PLACEMENT RULES - Recursive";
  rules: GlobalRule[];
}
export interface PlacementRule {
  /**
   * Type of constraint (positive/negative).
   */
  action: "allow-only" | "forbid" | "require";
  /**
   * Type of rule, e.g. 'distance'.
   */
  subject: string;
  /**
   * Human-readable reason for the rule.
   */
  reason: string;
  /**
   * Type of reason, either 'atomic' (short and combinable) or 'full' (long sentence).
   */
  reasonType?: "atomic" | "full";
  [k: string]: unknown;
}
